name: Docs

on: [push, pull_request]

jobs:
  docs:
    name: Docs

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    container: osgeo/proj-docs

    steps:
    - uses: actions/checkout@v2
    - name: Print versions
      shell: bash -l {0}
      run: |
          python3 --version
          DEBIAN_FRONTEND=noninteractive apt-get install pandoc texlive-xetex --assume-yes
          pip3 install pandoc
          sphinx-build --version
    - name: Lint .md files
      shell: bash -l {0}
      run: |
        if find . -name '*.md' | xargs grep -P '\t'; then echo 'Tabs are bad, please use four spaces in .md files.'; false; fi
    - name: HTML
      shell: bash -l {0}
      run: |
        pandoc -s DRAFT-SPEC.md -o DRAFT-SPEC.html

    - name: PDF
      shell: bash -l {0}
      run: |
        pandoc -s DRAFT-SPEC.md -o DRAFT-SPEC.pdf  --latex-engine=xelatex

    - uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: DRAFT-SPEC.pdf
    - uses: actions/upload-artifact@v2
      with:
        name: HTML
        path: DRAFT-SPEC.html

